title: Filip Smola
email: smola.filip@hotmail.com
description: Thoughts and random ideas of dubious use
locale: en-UK
baseurl: ""
url: "https://smola.me"
logo: #TODO
date_format: "%Y-%m-%d %H:%M"
copyright: "&copy; Filip Smola. Powered by <a href=\"https://jekyllrb.com\" rel=\"nofollow\">Jekyll</a> &amp; <a href=\"https://github.com/mmistakes/so-simple-theme\" rel=\"nofollow\">So Simple</a>. <a href=\"https://github.com/pilif0/pilif0.github.io\">Source</a>"

github_username: pilif0

remote_theme: mmistakes/so-simple-theme
markdown: kramdown
mathjax: true
permalink: /:categories/:title/
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

plugins:
  - jekyll-feed
#  - jekyll-paginate

# Category and tag linking to taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Liquid
liquid:
  error_mode: strict

## Paginate
#paginate: 10
#paginate_path: blog/page:num/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Filip Smola
  picture:
  email: smola.filip@hotmail.com

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/pilif0
    icon: fab fa-github-square
