title: Filip Smola
email: smola.filip@hotmail.com
description: Filip Smola's personal website.
locale: en-UK
baseurl: ""
url: "https://smola.me"
logo: #TODO
date_format: "%Y-%m-%d %H:%M"

github_username: pilif0

remote_theme: mmistakes/so-simple-theme
markdown: kramdown
mathjax: true
permalink: /:categories/:title/
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Liquid
liquid:
  error_mode: strict

# Paginate
paginate: 10
paginate_path: /page:num/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: false

# Site Author
author:
  name: Filip Smola
  picture:
  email: smola.filip@hotmail.com

# Footer Links
footer_links:
  - title: GitHub
    url: https://github.com/pilif0
    icon: fab fa-github-square
